# -*- coding: utf-8 -*-
"""Practice_sir_logistic_regr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBL6xLo7A7qpk6LN4qMf3JeTPh2xsQJP
"""

import pandas as pd

df = pd.read_excel("/content/drive/MyDrive/loan_logistic_regression_dataset.xlsx")

#Target variable is Loan_Approved (0/1), we'll build a Logistic Regression model.

df.head()

# Step 1: Import Libraries

df.info()

# Step 4: Check Missing Values

df.isnull().sum()

# Step 5: Separate Features and Target

x = df.drop('Loan_Approved',axis=1)
y = df['Loan_Approved']

# Step 6: Encode Categorical Columns

x = pd.get_dummies(x,drop_first=True)

x.head()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x,y,test_size=0.2,random_state=20
)

X_train.head()

y_train.head()

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

y_pred

import statsmodels.api as sm
X_train_const = sm.add_constant(X_train)

# Fit the logistic regression model
# Note: statsmodels expects data to be float/int, so convert bool columns if necessary
sm_model = sm.Logit(y_train, X_train_const.astype(pfloat)).fit_regularized(method='l1',alpha=0.1)
print(sm_model.summary())

"""# **Logistic Regression On mtcars dataset**"""

import pandas as pd

data = pd.read_excel("/content/drive/MyDrive/CDAC_DataBook.xlsx", sheet_name="mtcars")

data.head()



data = data.drop(["cyl",'disp','drat','qsec','vs','carb'], axis = 1)

data.head()

am_dummies = pd.get_dummies(data.am, drop_first=True).astype(int)
gear_dummies = pd.get_dummies(data.gear, drop_first = True).astype(int)

data = pd.concat([data, am_dummies, gear_dummies],axis = 1)

data.head()

data = data.drop(['am','gear'],axis = 1)

data.head()

data['mpg'].median()

import numpy as np

data['new_mpg'] = np.where(data['mpg'] > data['mpg'].median(),1,0)

data.head()

data = data.drop(['mpg'], axis=1)

data.head()

x = data.drop(["new_mpg"],axis=1)
y = data.new_mpg

y.head()

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=20, test_size=0.2)

import statsmodels.api as sm

x_train = sm.add_constant(x_train)
x_test = sm.add_constant(x_test)

x_train.head()

model = sm.Logit(y_train, x_train).fit()

print(model.summary())

